<a href="https://colab.research.google.com/github/vulpeAlba/Python_DA/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа по теме: "Введение в анализ данных. Операции над векторами и матрицами в NumPy"

In [2]:
import numpy as np

### Задание 1

Создать 12x12 единичную матрицу (с единицами по диагонали)

In [3]:
np.eye(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Задание 2 *

Создать 9x9 матрицу и заполнить её в шахматном порядке

In [19]:
chess = np.indices((9, 9)).sum(axis=0) % 2
print(chess)

[[0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]]


### Задание 3

Отсортировать произвольный вектор в порядке возрастания

In [32]:
np.random.seed(42)
vector = np.random.random(10)
print(sorted(vector))

[0.05808361216819946, 0.15599452033620265, 0.15601864044243652, 0.3745401188473625, 0.5986584841970366, 0.6011150117432088, 0.7080725777960455, 0.7319939418114051, 0.8661761457749352, 0.9507143064099162]


### Задание 4

Определить есть ли в произвольном двумерном массиве из целых чисел строки, в которых все значения равны 4.

In [ ]:
np.random.seed(42)
fourth_array = np.random.randint(3, 5,(8, 3))

False

### Задание 5

Создайте массив из 6 элементов, 5 из которых равны 0, последний элемент должен быть равен 1

array([0., 0., 0., 0., 0., 1.])

### Задание 6

Укажите индекс 9 элемента в массиве 2х3х2

(1, 1, 1)